[package]
name = "charlotte_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = {version = "*", features = ["spin_no_std"]}
limine = "*"
spin = {verison = "0.9.8", features = ["ticket_mutex"]}
x86_64 = "*"