[package]
name = "charlotte_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "charlotte_core"
test = false
bench = false

[build-dependencies]
cc = "*"
walkdir = "*"

[dependencies]
ignore-result = "*"
limine = "0.2.0"
spin = {version = "*", features = ["ticket_mutex"]}
